#!/bin/bash

ENV_FILE="deployments/.env"

POSTGRES_HOST="postgres"
POSTGRES_PORT="5432"
POSTGRES_DB="avito_db"
POSTGRES_USER="jerey"
POSTGRES_PASSWORD="jereyjerey"
POSTGRES_SSLMODE="disable"
SECRET_KEY=$(openssl rand -hex 32)
ACCESS_TOKEN_EXPIRATION=30  #  minutes
REFRESH_TOKEN_EXPIRATION=14 # days

echo "POSTGRES_HOST=${POSTGRES_HOST}" > $ENV_FILE
echo "POSTGRES_PORT=${POSTGRES_PORT}" >> $ENV_FILE
echo "POSTGRES_DB=${POSTGRES_DB}" >> $ENV_FILE
echo "POSTGRES_USER=${POSTGRES_USER}" >> $ENV_FILE
echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> $ENV_FILE
echo "POSTGRES_SSLMODE=${POSTGRES_SSLMODE}" >> $ENV_FILE
echo "SECRET_KEY=${SECRET_KEY}" >> $ENV_FILE
echo "ACCESS_TOKEN_EXPIRATION=${ACCESS_TOKEN_EXPIRATION}" >> $ENV_FILE
echo "REFRESH_TOKEN_EXPIRATION=${REFRESH_TOKEN_EXPIRATION}" >> $ENV_FILE